#### 1. Arrays

In [1]:
import numpy

def arrays(arr):
    fresult =numpy.array(arr[::-1],float)
    return fresult

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


#### 2.Shape and Reshape

In [2]:
import numpy

arr = numpy.array(input().strip().split(),int)
result = numpy.reshape(arr,(3,3))
print(result)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 3. Transpose and Flatten 

In [5]:

n,m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(m)], int)
print (array.transpose())
print (array.flatten())


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


#### 4.Concatenate

In [6]:
import numpy
n,m,p = map(int,input().split())
array1 = numpy.array([input().strip().split() for _ in range(n)], int)
array2 = numpy.array([input().strip().split() for _ in range(m)], int)
print(numpy.concatenate((array1,array2),axis=0))

4 3 2
1 2
1 2
1 2
1 2
1 2
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]]


#### 5. Zeros and Ones 

In [7]:
import numpy

n = tuple(map(int,input().split()))
print(numpy.zeros(n,dtype=numpy.int))
print(numpy.ones(n,dtype=numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


#### 6.Eye and Identity

In [8]:
n,m = map(int,input().split())
numpy.set_printoptions(legacy='1.13')
print(numpy.eye(n,m))


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### 7. Array Mathematics

In [9]:
n,m = map(int,input().split())
a , b = (numpy.array([input().split() for _ in range(n)],int) for _ in range(2))
print(numpy.add(a,b))
print(numpy.subtract(a,b))
print(numpy.multiply(a,b))
print(numpy.divide(a,b))
print(numpy.mod(a,b))
print(numpy.power(a,b))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[ 0.2         0.33333333  0.42857143  0.5       ]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


#### 8. Floor, Ceil and Rint

In [10]:
array1 = numpy.array(input().strip().split(),float)
numpy.set_printoptions(legacy='1.13')
print(numpy.floor(array1))
print(numpy.ceil(array1))
print(numpy.rint(array1))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


#### 9.  Sum and Prod

In [11]:
n,m = map(int,input().split())
a  = (numpy.array([input().split() for _ in range(n)],int))
print(numpy.prod(numpy.sum(a,axis=0)))

2 2
1 2
3 4
24


#### 10. Min and Max

In [12]:
n,m = map(int,input().split())
a  = (numpy.array([input().split() for _ in range(n)],int))
print(numpy.max(numpy.min(a,axis=1),axis=None))


4 2
2 5
3 7
1 3
4 0
3


#### 11.Mean, Var, and Std

In [3]:
import numpy
n, m = map(int,input().split())
a = numpy.array([input().split() for _ in range(n)],int)
numpy.set_printoptions(legacy='1.13')
print(numpy.mean(a,axis=1))
print(numpy.var(a,axis=0))
print( numpy.std(a))


2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


#### 12.Dot and Cross 

In [6]:
n=int(input())
array1 = numpy.array([input().split() for _ in range(n)], int)
array2 = numpy.array([input().split() for _ in range(n)], int)
print(numpy.dot(array1,array2))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


#### 13.Inner and Outer 

In [7]:
array1 = numpy.array(input().split(), int)
array2 = numpy.array(input().split(), int)
print(numpy.inner(array1,array2))
print(numpy.outer(array1,array2))

0 1
2 3
3
[[0 0]
 [2 3]]


#### 14.Polynomials

In [8]:
n = list(map(float,input().split()))
m = input()
print(numpy.polyval(n,int(m)))

1.1 2 3
0
3.0


#### 15. Linear Algebra

In [9]:
n = int(input())
array1 = numpy.array([input().split() for _ in range(n)],float)
numpy.set_printoptions(legacy='1.13')
print(numpy.linalg.det(array1))

2
1.1 1.1
1.1 1.1
0.0
